Update custom-updates-ubuntu

diff --git a/custom-updates-ubuntu b/custom-updates-ubuntu
--- a/custom-updates-ubuntu
+++ b/custom-updates-ubuntu
@@ -1,9 +1,10 @@
-#!/bin/bash -x
+#!/bin/bash
 #This script allows for update, upgrade, and dist-upgrade
 #Author: Stephen J Kennedy
-#version 1.1
+#version 1.2
+#DEBUG used with -x (reports shell name, line number, and associated function)
+PS4='+ $BASH_SOURCE : $LINENO : ${FUNCNAME[0]} ()'
 
-THISHOST=$(hostname -f)
 DATE=$(date +"%F")
 TIME=$(date +"%H:%M:%S")
 LOGPATH="/bin/custom"
@@ -22,24 +23,25 @@ if [ $? -ne 0 ]
       $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
    else
       echo "Success!"
-      $MAIL -s ${DATE}-${THISHOST}  $TO < $LOG
+      $MAIL -s ${DATE}-${HOSTNAME}  $TO < $LOG
 fi
 }
 
 #Auto-update and upgrade process. Checks for need to dist-upgrade and
 #exits with return 3 if dist-upgrade needed.
+#Auto-update and upgrade process. Checks for need to dist-upgrade and
+#exits with return 3 if dist-upgrade needed.
 
 autoUpdate (){
 echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
-sudo apt-get update
+#sudo apt-get update
 
 for UPDATE in $UPDATE
 do
    echo "Starting apt-get ${UPDATE}..." >> $LOG
    if [ ${UPDATE} = "dist-upgrade" ]
       then
-        apt-get --assume-no $UPDATE
-        echo "DIST-UPGRADE required" >> $LOG return 3
+        apt-get --assume-no $UPDATE || echo "DIST-UPGRADE required" >> $LOG return 3
    else
         apt-get --assume-yes $UPDATE >> $LOG ||  return 1
         echo "apt-get ${UPDATE} successful!" >> $LOG
