version 1.1
removed auto-upgrade for dist-upgrade and instead now checks to see if needed.

diff --git a/custom-updates-ubuntu b/custom-updates-ubuntu
--- a/custom-updates-ubuntu
+++ b/custom-updates-ubuntu
@@ -13,7 +13,7 @@ LOG="${LOGPATH}/log/${DATE}-${PID}-log"
 TEMP="${LOGPATH}/.temp"
 MAIL=/usr/bin/mail
 TO="medicup@gmail.com"
-UPDATE="upgrade dist-upgrade autoremove" #options for autoUpdate do statement
+UPDATE="upgrade dist-upgrade" #options for autoUpdate do statement
 
 #mail Function uses mail to distribute results of autoUpdate
 mailOutput(){
@@ -27,20 +27,24 @@ if [ $? -ne 0 ]
 fi
 }
 
-#autoUpdate function uses a do statement that will run until error or
-#all update options are processed. It provides a start and success
-#response that is exported to a text file
+#Auto-update and upgrade process. Checks for need to dist-upgrade and
+#exits with return 3 if dist-upgrade needed.
 
 autoUpdate (){
 echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
 sudo apt-get update
 
-
 for UPDATE in $UPDATE
 do
    echo "Starting apt-get ${UPDATE}..." >> $LOG
-   apt-get --assume-yes $UPDATE >> $LOG ||  return 1
-   echo "apt-get ${UPDATE} successful!" >> $LOG
+   if [ ${UPDATE} = "dist-upgrade" ]
+      then
+        apt-get --assume-no $UPDATE
+        echo "DIST-UPGRADE required" >> $LOG return 3
+   else
+        apt-get --assume-yes $UPDATE >> $LOG ||  return 1
+        echo "apt-get ${UPDATE} successful!" >> $LOG
+   fi
 done
 }
 
